"use client";

import React from 'react';
import Container from '@mui/material/Container';
import SpacedHeader from '@/common/SpacedHeader';
import ManaCost from '@/common/mana-cost/ManaCost';
import Typography from '@mui/material/Typography';
import {styled} from '@mui/system';
import Link from '@mui/material/Link';
import Grid from '@mui/material/Grid';
import Divider from '@mui/material/Divider';

const SubSectionHeader = styled(Typography)({
  marginTop: '20px',
  marginBottom: '20px',
});

const CardImage = styled('img')({
  maxWidth: '400px',
  width: '100%',
});

const FullWidthImage = styled('img')({
  maxWidth: '100%',
});

export default function YourFirstVrd() {
  return (
    <Container maxWidth="lg" >
      <SpacedHeader
        component="h1"
        sx={{marginTop: 10}}
        variant="h2"
      >{'Your First VRD'}</SpacedHeader>
      <Typography
        color="text.secondary"
        sx={{marginBottom: '20px', marginLeft: '20px'}}
        variant="subtitle1"
      >{'Written by: CommonOpponent on December 9, 2021'}</Typography>

      <Typography paragraph>Vintage Rotisserie Draft can be an intimidating format to approach. The name Vintage evokes in many players a sense of overwhelming dread, not simply because of the sheer volume of the card pool, but for the misconception that most games of Vintage are super fast one or two turn affairs. It’s certainly true that <strong>some</strong> games can be decided quickly, but more often than not you will have an interactive game, possibly even one that goes quite long. The card pool is indeed <strong>deep</strong>, however the actual number of regularly played cards is in fact not any more extensive than formats like Legacy or Modern.</Typography>
      <Typography paragraph>You <strong>can</strong> (and should!) give VRD a try if it seems at all interesting to you, and I’d like to help the curious reader avoid some of the common pitfalls that await the rookie entrant. With a bit of preparation, any Magic player can partake in and enjoy this rewarding nascent format. </Typography>
      <SubSectionHeader
        component="h2"
        variant="h3"
      >Learn From the Past</SubSectionHeader>
      <CardImage alt="Learn from the Past magic card"
        src="https://c1.scryfall.com/file/scryfall-cards/png/front/3/4/347c6e76-dba4-4448-a4f4-d9591d4539c7.png?1562784558"
      />
      <Typography paragraph>The best way to learn the fundamentals of the format is going to be to simply <Link href="https://www.youtube.com/channel/UCpwS9X2A-5pmo1txhyD7eoA">watch a couple of <strong>recent</strong> VRD drafts</Link>. Not only will this help familiarize you with the particular cards that will be used, but the excellent commentary from the St. Lotus crew will help fill you in as to why each drafter is prioritizing the cards they do in each round. Watching experienced players draft their deck is arguably more valuable to a new player than even drafting themselves without the benefit of this learning exercise. </Typography>
      <Typography paragraph>There are reasons I specifically recommend viewing recent drafts, because VRD changes rapidly and will continue to do so for the foreseeable future. Firstly, VRD is more sensitive to new printings than Vintage or Legacy because of its nature as a 40 card singleton format. Secondly, it is played in so much less volume than any other format. This means there is a much less established metagame, and the player base is learning together with each and every set of event results. </Typography>
      <Typography paragraph>If the time requirement seems off-putting, I would recommend both chunking out a draft into manageable pieces (30-90 minutes at a time depending what works for you) and speeding up the playback. Research suggests that people enjoy sped up audio and video more and more as they are acclimated to it, and it’s a great way to condense learning materials into briefer time windows. YouTube allows custom playback speed, so you can start at a barely noticeable x1.15 speed if you’re skeptical, but most people will find themselves quickly ramping up to around x1.5. </Typography>
      <Typography paragraph>Watching the actual matches be played is also valuable as it will help contextualize why many of the cheap interactive spells are so fought over early on. While less essential, this will also help you be prepared for the environment your deck will face, as well as begin to familiarize you with the common patterns of interactions.  </Typography>
      <Typography paragraph>Reading the other great articles available on St. Lotus is also a great way to learn about the norms of the format, particularly <Link href="https://stlotus.org/build/index.html#/articles/2021-11-25/Combos%20in%20VRD">Mark Katerberg’s <strong>excellent</strong> compendium of the most commonly played Combos in the format</Link>. Combos are the unifying force of the format, and important to learn about. If you are not playing an Aggro deck, you should almost certainly be playing a Combo as your win condition, even if it is as rudimentary as <Link href="https://scryfall.com/card/usg/96/show-and-tell">Show and Tell</Link> + <Link href="https://scryfall.com/card/roe/4/emrakul-the-aeons-torn">Emrakul</Link>. VRD decks are too adept at winning on the spot if given the chance to rely solely on multiple attacks from “midrange” threats as your finisher. Even Aggro decks can sometimes struggle to close out a game in time if they are not prepared to disrupt an opposing Combo. </Typography>
      <SubSectionHeader
        component="h2"
        variant="h3"
      >Prepare More Than One Plan</SubSectionHeader>
      <CardImage alt="Contingency Plan magic card"
        src="https://c1.scryfall.com/file/scryfall-cards/png/front/9/e/9edb76bd-db4b-4279-8eaa-dfdf5952eafc.png?1576384047"
      />
      <Typography paragraph>You won’t know your position in the draft order until the event begins, and as such you will not know what cards and therefore strategies are going to be available to you going in. This is not to say that multiple players at a table cannot play very similar archetypes, but there is a point at which it is in your best interest to pivot off a preferred strategy. If you go in dead-set on drafting B/R Aggro, but two other players clearly signal that this is their plan, you will build a stronger deck and have more fun by having backup plans and deciding as early as possible to move to one of them.</Typography>
      <Typography paragraph>As we’ll cover in a later section, space is <strong>extremely</strong> limited in Rotisserie decks. You cannot afford to have several selections which don’t ultimately benefit your finished deck, even if only as a potent sideboard option. Waiting too long to pivot out of a crowded lane, or dipping into multiple paths through indecision will quickly lead you to an ineffective deck and frustrating hands with low synergy. Once you have made sacrifices to better position yourself in a new deck you need to commit to building the best version of that deck you can, even if you find yourself uncertain that it’s where you should have ended up. Once you accumulate 4, 5, 6 dead cards in your draft you will have put yourself at such a significant disadvantage that your deck will struggle and your matches will become frustrating. </Typography>
      <Typography paragraph>Each archetype is going to vary in the number of drafters it can support depending on the depth of the card pool of each strategy. This is why it is vital that you familiarize yourself with more than one deck archetype and the card pool that supports them in order to give yourself the confidence and flexibility to know whether you need to bail or stay the course. I believe that choosing three decks to focus on will work best for most first time players without being too overwhelming. Choosing to narrow that to two, or get ambitious and explore four or more is a matter of taste and time investment.  </Typography>
      <Typography paragraph>Multiple players are going to end up in <ManaCost manaCost="{U}" /> (and likely in <ManaCost manaCost="{B}" />), and this is nothing to worry about if you are one of them. Control, Combo, and even Tempo are viable focuses for a <ManaCost manaCost="{U}" /> deck to have, so as many as 5 <ManaCost manaCost="{U}" />-heavy drafters can coexist, though that is the upper limit, so it becomes beneficial to at the very least explore ways to use your existing <ManaCost manaCost="{U}" /> cards with another focus color that is now likely being under-drafted at the table. (It’s probably <ManaCost manaCost="{W}" /> or <ManaCost manaCost="{G}" />) </Typography>
      <Typography paragraph>Many players seem uncomfortable having a second Artifact-heavy drafter at the table, but the archetype is quite deep and can comfortably support two drafters, especially if one of them is playing an aggressive Affinity-like build. Similarly, there can easily be two Aggro decks with <ManaCost manaCost="{R}" /> if one has <ManaCost manaCost="{B}" /> as its second color, and the other is drawing from <ManaCost manaCost="{W}" /> and/or <ManaCost manaCost="{G}" />.</Typography>
      <Typography paragraph>A niche archetype like Reanimator or Poison is not worth fighting a second drafter over. This will result in both of you having under-powered decks and likely poor results. However, as previously mentioned you cannot afford to simply forfeit several picks. Once you decide to pivot it becomes imperative to find ways to salvage as much of your card pool as possible. For example, if a second player insists on moving into Reanimator don’t discard your <Link href="https://scryfall.com/card/avr/106/griselbrand">Griselbrand</Link> in despair, consider moving into a <Link href="https://scryfall.com/card/usg/218/sneak-attack">Sneak</Link> and <Link href="https://scryfall.com/card/usg/96/show-and-tell">Show</Link> build. Alternatively, <Link href="https://scryfall.com/card/tmp/151/reanimate">Reanimate</Link> is powerful for its low mana cost, which means it can still be put to good use rebuying powerful Aggro threats like <Link href="">Dark Confidant</Link> or <Link href="https://scryfall.com/card/mh2/397/dauthi-voidwalker">Dauthi Voidwalker</Link>.</Typography>
      <Typography paragraph>Conflict over such narrow archetypes is not common though, and more often you will find yourself needing to lateral in more subtle ways. Let’s say you’d planned on being a <ManaCost manaCost="{U}" />/<ManaCost manaCost="{B}" /> Combo deck, and have already selected the likes of <Link href="https://scryfall.com/card/lea/262/mox-jet">Mox Jet</Link> and <Link href="https://scryfall.com/card/lea/104/demonic-tutor">Demonic Tutor</Link> when it becomes clear multiple other players are dead set on heavy <ManaCost manaCost="{B}" /> based decks. You may want to move aggressively on premium mana fixing while also planning on cards like <Link href="https://scryfall.com/card/plc/165/urborg-tomb-of-yawgmoth">Urborg, Tomb of Yawgmoth</Link> or <Link href="https://scryfall.com/card/5dn/143/pentad-prism">Pentad Prism</Link> later on in order to maintain your powerful <ManaCost manaCost="{B}" /> cards. You’re no longer going to be the <Link href="https://scryfall.com/card/ice/154/necropotence">Necropotence</Link> wielding Combo deck you had envisioned, but DT will be a fine splash in a <ManaCost manaCost="{U}" />/<ManaCost manaCost="{W}" />/<ManaCost manaCost="{B}" /> Esper deck sporting complementary spells like <Link href="https://scryfall.com/card/mir/14/enlightened-tutor">Enlightened Tutor</Link>. </Typography>
      <Typography paragraph>Sometimes a color change isn’t even the necessary shift, but rather a change in focus within the same color. If the Aggro lane gets crowded early it doesn’t necessarily mean you need to be out of <ManaCost manaCost="{R}" />. Your <Link href="https://scryfall.com/card/lea/161/lightning-bolt">Lightning Bolt</Link> and <Link href="https://scryfall.com/card/tmp/294/lotus-petal">Lotus Petal</Link> will serve you well in a <Link href="https://scryfall.com/card/roe/165/splinter-twin">Splinter Twin</Link>/<Link href="https://scryfall.com/card/chk/175/kiki-jiki-mirror-breaker">Kiki-Jiki</Link> Combo deck. Finding paths forward that maintain as much effectiveness from as many previous selections as possible will help ensure you are able to strike the delicate spatial balance between your mana base, sideboard, and action spells. </Typography>
      <SubSectionHeader
        component="h2"
        variant="h3"
      >RTFC</SubSectionHeader>
      <CardImage alt="Port Inspector magic card"
        src="https://c1.scryfall.com/file/scryfall-cards/png/front/e/f/ef25d969-68d9-4580-bb29-f72bd5646a3d.png?1562383980"
      />
      <Typography paragraph>Read the ding dang diddly cards, y’all. <Link href="https://scryfall.com">Scryfall</Link> is your best friend while researching this format. With cards from so many eras interacting, it’s very easy to forget exactly what a card does, how it works, or how it will interact with the format. Whether you are investigating potential archetypes, compiling a list of target cards, or considering a pick in-draft, if you aren’t 100% certain go have a quick look.</Typography>
      <Typography paragraph>To give a real life example; in my first draft I thought I would brush off a card I believed would be a versatile finisher for a Control deck, <Link href="https://scryfall.com/card/dtk/217/dragonlord-dromoka">Dragonlord Dromoka</Link>. I figured it would obviously fight the counter-heavy <ManaCost manaCost="{U}" /> decks, while also being an MVP against the Aggro decks with its combination of Lifelink and Vigilance. The problem being that it <strong>doesn’t</strong> have Vigilance, which believe it or not cost me at least two games and likely a match. </Typography>
      <Typography paragraph>This was an easy mistake to avoid, and a dangerously easy one to make given the wide range of cards that enter consideration. Do yourself a favor and establish the habit of pulling up each card you aren’t intimately familiar with. There are over Twenty Thousand unique Magic cards, and we’ve all had the experience of recalling details of a card incorrectly. You cannot and will not get every detail right, so before you draft a card or even slot it into your list of targets go have a look, it only costs a moment. </Typography>
      <SubSectionHeader
        component="h2"
        variant="h3"
      >Read The Table</SubSectionHeader>
      <CardImage alt="Read the Runes magic card"
        src="https://c1.scryfall.com/file/scryfall-cards/png/front/b/c/bc148c21-cbe6-4cea-899b-e62501b59a00.png?1562939380"
      />
      <Typography paragraph>Once your draft has started and the picks are flying, the most essential thing to do is pay attention to what the other drafters are up to. Many players will tip their hand about what they’re planning as early as round 3 or 4, though many things will be apparent within just the first two rounds. Most players will signal one of their colors with a Mox or <Link href="https://scryfall.com/card/lea/47/ancestral-recall">Recall</Link> in round 1, and while it may not seem like much it begins to paint a picture. A player in Seat 1 who takes <Link href="https://scryfall.com/card/ulg/45/tinker">Tinker</Link> and <Link href="https://scryfall.com/card/lea/274/time-vault">Time Vault</Link> on the 2-3 turn is pretty locked in to an Artifact heavy <ManaCost manaCost="{U}" /> deck. If a player drafts <Link href="https://scryfall.com/card/phpr/5/mana-crypt">Mana Crypt</Link> and <Link href="https://scryfall.com/card/lea/259/mana-vault">Mana Vault</Link>, they are similarly very likely to play an Artifact heavy deck. </Typography>
      <Typography paragraph>Aside from finding your own “lane”, there are two effects to be aware of as you see the situation develop. First, the value of certain cards will fluctuate depending on the competition you will face. <Link href="https://scryfall.com/card/dtk/182/display-of-dominance">Display of Dominance</Link> is a fine card, but its strength will vary from one draft to the next. If you are facing only two <ManaCost manaCost="{U}" />-heavy decks looking to control the board with Countermagic, and just a single <ManaCost manaCost="{B}" /> drafter then cards like <Link href="https://scryfall.com/card/dtk/182/display-of-dominance">Display</Link> or <Link href="https://scryfall.com/card/m11/162/autumns-veil">Autumn’s Veil</Link> are unlikely to be important to your success. Conversely, in a field chalk full of <ManaCost manaCost="{U}" /> drafters with multiple <ManaCost manaCost="{B}" /> drafters as well, they begin to look much more appealing to the <ManaCost manaCost="{G}" /> mage. </Typography>
      <Typography paragraph>This dynamic applies to a wide range of cards, for instance board sweepers are lightly played in VRD aside from <Link href="https://scryfall.com/card/lea/3/balance">Balance</Link>, but if you are facing three or four creature heavy decks it is likely time to consider some lesser played cards for your sideboard like <Link href="https://scryfall.com/card/xln/34/settle-the-wreckage">Settle the Wreckage</Link>, <Link href="https://scryfall.com/card/leg/28/moat">Moat</Link>, <Link href="https://scryfall.com/card/ice/214/pyroclasm">Pyroclasm</Link>, <Link href="https://scryfall.com/card/c13/96/toxic-deluge">Toxic Deluge</Link>, etc. </Typography>
      <Typography paragraph>The second pressure upon these niche cards is Demand. Even once you know a card like <Link href="https://scryfall.com/card/dtk/182/display-of-dominance">Display</Link> is going to be effective against the field you will be facing, you must also consider whether anyone else at the table is likely to snag the card from you. If there’s a second <ManaCost manaCost="{G}" /> drafter at the table then such an interactive card will likely warrant a mid-round selection. Conversely, if you’re the only drafter showing <ManaCost manaCost="{G}" /> through 12 rounds then you will be able to “float” these kinds of cards much later. That said, VRD decks can be versatile with strong mana, so even in the aforementioned scenario, a player with multiple Fetchlands and a <Link href="https://scryfall.com/card/sth/138/mox-diamond">Mox Diamond</Link> should be viewed warily. </Typography>
      <Typography paragraph>The element of demand is not solely swayed by color affiliation though, as it is very sensitive to strategy. For instance, I mentioned in section two that multiple decks may end up heavily Artifact focused, with very divergent intentions. Let’s say you’re an Affinity drafter with a <Link href="https://scryfall.com/card/ulg/45/tinker">Tinker</Link> — <Link href="https://scryfall.com/card/lea/274/time-vault">Time Vault</Link> drafter showing entirely mono-<ManaCost manaCost="{U}" /> intentions thus far. <Link href="https://scryfall.com/card/som/179/mox-opal">Mox Opal</Link> will be a point of contention between you in the early draft because of its explosive speed, but the presence of this drafter may not actually put significant Demand pressure on a card like <Link href="https://scryfall.com/card/aer/184/spire-of-industry">Spire of Industry</Link> or <Link href="https://scryfall.com/card/mrd/281/glimmervoid">Glimmervoid</Link>. An almost mono-<ManaCost manaCost="{U}" /> deck will not want to spend a mid-round pick on fixing, so even though you want these to enable powerful splash cards like <Link href="https://scryfall.com/card/mrd/54/thoughtcast">Thoughtcast</Link> or <Link href="https://scryfall.com/card/mrd/106/shrapnel-blast">Shrapnel Blast</Link> you can likely push these selections until late-round picks. Getting a sense for when you need to prioritize a card and when it can be safely floated is a valuable skill that will only come with experience. Which leads us to our next topic:</Typography>
      <SubSectionHeader
        component="h2"
        variant="h3"
      >Reverse Engineer Your Draft </SubSectionHeader>
      <CardImage alt="Reverse Engineer magic card"
        src="https://c1.scryfall.com/file/scryfall-cards/png/front/d/5/d56f8cca-6b8f-45ea-926f-161938716ee9.png?1576381545"
      />
      <Typography paragraph>When you’re researching your desired archetypes you should draw up some very rough outlines of what a finished deck would look like for each archetype. You’ll never get all the cards you want, and in fact it’s not terribly important whether you get that <Link href="https://scryfall.com/card/lrw/145/thoughtseize">Thoughtseize</Link> early, or have to settle for a <Link href="https://scryfall.com/card/usg/132/duress">Duress</Link> later on. Rather it’s helpful to have an idea beforehand “ok, I want about 3 Cantrips” or “I want to spend 4 spots on versatile removal”. This will paint a clearer picture of the amount of deck space you have left to work with as your draft progresses. </Typography>
      <Typography paragraph>It is easy as an observer to underestimate just how restrictive 46 selections can really be. Your mana-base and your sideboard are essentially clashing for spatial and temporal priority, and you will need to decide how much to value each in terms of both raw card number as well as round selection. You <strong>can</strong> have perfect mana, but you will likely have just 5 or 6 sideboard cards. You <strong>can</strong> have a plethora of sideboard options, but you’ll likely be strictly limited to a single splash color to accent your primary color. This is a delicate balance, and one without a “correct” ratio, as the optimal balance will be different for each deck depending on its needs. </Typography>
      <Typography paragraph>In addition to managing these concerns via deck outlines, you will also be faced with probably <strong>the</strong> single most challenging aspect of VRD; when to draft each particular card. Even the most experienced VRD drafters will come away from every single draft with at least a couple instances where they’ll readily admit “ugh, I wish I’d just grabbed [INSERT CARD] before it went. I knew I wanted it!” The difficulty stems from the fact that this decision of prioritization is made round after round, and each of the pressures we’ve discussed already play into it with dynamic action each and every time. It’s the difficult skill at the heart of the game, and you shouldn’t be hard on yourself when an opponent inevitably snags a card out from under you. This will often help you realize in retrospect that the card in question was in fact more important for your deck than some of the cards selected in previous rounds, and should have been prioritized higher. </Typography>
      <Typography paragraph>Some of the concepts we’ve covered can help guide you through your first drafts, when you don’t have the benefit of those lessons derived from experience. To continue our previous example, let’s again put ourselves in the position of drafting Affinity. What we need to do is start sketching out what cards we can safely presume will be available with our late-round selections in order to narrow our options for what we should select earlier. Unless there is some kind of <Link href="https://scryfall.com/card/atq/81/mishras-workshop">Workshop</Link> — <Link href="https://scryfall.com/card/wwk/127/lodestone-golem">Lodestone Golem</Link> — <Link href="https://scryfall.com/card/aer/181/walking-ballista">Walking Ballista</Link> type deck at the table, no one else is going to be interested in <Link href="https://scryfall.com/card/5dn/113/cranial-plating">Cranial Plating</Link>. On the other hand, any decks full of bodies, be they mana dorks or Aggro critters, would benefit from a <Link href="https://scryfall.com/card/dst/140/skullclamp">Skullclamp</Link>. <Link href="https://scryfall.com/card/5dn/113/cranial-plating">Plating</Link> can safely be slotted as a late-round pick, while <Link href="https://scryfall.com/card/dst/140/skullclamp">Clamp</Link> should be pushed higher the more creature-based decks we see. In fact <Link href="https://scryfall.com/card/dst/140/skullclamp">Clamp</Link> may potentially go <strong>very</strong> highly, as its mana cost is both low and colorless, keeping its potential Demand high. </Typography>
      <Typography paragraph>Similarly, the <Link href="https://scryfall.com/card/ulg/45/tinker">Tinker</Link> — <Link href="https://scryfall.com/card/lea/274/time-vault">Time Vault</Link> deck isn’t planning to win with damage, and will have no interest in <Link href="https://scryfall.com/card/mrd/106/shrapnel-blast">Shrapnel Blast</Link>, and no one else will have the artifact count to support it. We can plan on getting that with potentially our literal last pick, however they may well be interested in a card like <Link href="https://scryfall.com/card/mrd/54/thoughtcast">Thoughtcast</Link>, so as the draft progresses and our list of target cards starts to look more niche to our deck we may want to prioritize it over other niche cards, as yet one players remains who may also want access to it. They don’t want our <Link href="https://scryfall.com/card/dst/163/blinkmoth-nexus">Blinkmoth Nexus</Link>, but they’re surely going to take <Link href="https://scryfall.com/card/mrd/283/seat-of-the-synod">Seat of the Synod</Link> and <Link href="https://scryfall.com/card/dst/164/darksteel-citadel">Darksteel Citadel</Link> with mid-round picks. By keeping track of our opponents’ intentions and possibilities we can loosely sort our remaining target cards by the possible Demand presented by our potential competitors. </Typography>
      <Typography paragraph>A Rotisserie draft will typically divide organically into three phases. The first dozen rounds or so constitute the early draft where everyone is establishing their lanes and fighting over the most versatile pieces that benefit a variety of strategies. These rounds will be dominated by mana accelerants, game ending Combo pieces, cheap interactive spells like discard and countermagic, and general broken cards, then transitioning into premium mana fixing. </Typography>
      <Typography paragraph>The middle rounds are a grueling balancing act of priorities. There will be conflict between similar archetypes over utility spells and enablers, as well as continued focus on mana fixing. The less premium Combo pieces will also be claimed in these rounds. Some players will have floated the second half of their Combo, some will now move to acquire the ones still available, and it is not uncommon for players to add a second Combo for resilience, versatility, or redundancy as the case may be. (aka Two Card Monte) Premium sideboard options will also start to be selected, and remember that the cards which are colorless and/or cheap will be selected earlier. Anyone can cast <Link href="https://scryfall.com/card/wth/154/null-rod">Null Rod</Link> or <Link href="https://scryfall.com/card/ulg/125/defense-grid">Defense Grid</Link>, so the Demand on them will be high.</Typography>
      <Typography paragraph>The final dozen rounds or so feature increasingly siloed decisions and less interplay, since the viable card pool for each player is now smaller with much less overlap between them. The focus will be on low Demand sideboard cards, bargain bin mana fixing options, and the very niche cards no one else at the table is likely to want. </Typography>
      <SubSectionHeader
        component="h2"
        variant="h3"
      >Know Yourself</SubSectionHeader>
      <CardImage alt="Self-Inspector magic card"
        src="https://c1.scryfall.com/file/scryfall-cards/png/front/3/d/3d05c6c2-4bb3-468a-b23c-b0425a9982f1.png?1576383395"
      />
      <Typography paragraph>The final and most important element of drafting is to make sure to have <strong>fun</strong>. We all have different backgrounds with Magic, and only you know what your experience and preference will lead you to enjoy playing. Whether you’re a lifelong hardcore Draw-Go Control devotee or you’ve spent a decade playing Legacy Death and Taxes, tailor your preparation toward decks that you will actually like and enjoy playing. Don’t force yourself to play a convoluted <Link href="https://scryfall.com/card/lea/192/fastbond">Fastbond</Link> Combo if it holds little appeal to you simply because you think it’s strong or you’re “supposed to”. You’re not going to have fun playing a deck that isn’t interesting to you.</Typography>
      <Typography paragraph>That isn’t to say you shouldn’t play something you’re uncomfortable or unfamiliar with if it is interesting to you. The worst thing that can happen is that you lose your matches, but you can have plenty of fun learning while losing matches. Losing is only a failure if you learn nothing from it, and you’d be hard pressed not to learn quite a bit about VRD from your first couple of drafts. </Typography>
      <Typography paragraph>Some people will relish the challenge VRD offers playing wholly unfamiliar decks, while others will delight in refining familiar strategies to conquer new obstacles. We each have our ways of finding fun in VRD, and I encourage you to find yours someday soon. </Typography>

      <Typography
        color="text.secondary"
        component="h2"
        sx={{marginTop: '60px'}}
        variant="h4"
      >About the author:</Typography>
      <Divider sx={{margin: '10px 0 30px'}}/>
      <Grid container
        sx={{marginBottom: '40px'}}
      >
        <Grid item
          sm={2}
          xs={3}
        >
          <FullWidthImage src="/authors/common.jpg"
            sx={{borderRadius: '10px'}}
          />
        </Grid>
        <Grid alignItems="center"
          container
          flexGrow={1}
          item
          sm={10}
          xs={9}
        >
        <Typography
          color="text.secondary"
          sx={{verticalAlign: 'middle', marginLeft: '20px'}}
          variant="subtitle2"
        >CommonOpponent started with casual MTG in the mid 90s, eventually playing every format but Commander to various extents over the years. A Limited specialist, he has been an avid spectator of VRD for many years, now happily drafting and theorycrafting in the <Link href="https://discord.gg/nxBPYXn">VRD Discord</Link>. His favorite cards are <Link href="https://scryfall.com/card/chk/62/gifts-ungiven">Gifts Ungiven</Link>, <Link href="https://scryfall.com/card/wth/66/doomsday">Doomsday</Link>, and <Link href="https://scryfall.com/card/ulg/80/goblin-welder">Goblin Welder</Link>.</Typography>
        </Grid>
      </Grid>
    </Container>
  );
}
